name: Apache Flink ClickHouse Connector Tests CI (Scala)

on: [push]

jobs:
  test-flink-17:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        clickhouse: [ "23.7", "24.3", "latest", "cloud" ]
        flink: [ "1.17.2", "1.18.1", "1.19.3", "1.20.2"]
    name: Apache Flink ${{ matrix.flink }} ClickHouse Connector tests with ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Check for Cloud Credentials
        id: check-cloud-credentials
        run: |
          if [[ "${{ matrix.clickhouse }}" == "cloud" && (-z "${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}" || -z "${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}") ]]; then
            echo "SKIP_STEP=true" >> $GITHUB_ENV
          else
            echo "SKIP_STEP=false" >> $GITHUB_ENV
          fi
        shell: bash
      - uses: actions/checkout@v3
        if: env.SKIP_STEP != 'true'
      - name: Set up JDK 21
        if: env.SKIP_STEP != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
      - name: Setup and execute Gradle 'test' task
        if: env.SKIP_STEP != 'true'
        uses: gradle/gradle-build-action@v2
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
          CLICKHOUSE_CLOUD_HOST: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}
          CLICKHOUSE_CLOUD_PASSWORD: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}
          FLINK_VERSION: ${{ matrix.flink }}
        with:
          arguments: :flink-connector-clickhouse-1.17:runScalaTests
  test-flink-2:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        clickhouse: [ "23.7", "24.3", "latest", "cloud" ]
    name: Apache Flink 2.0.0 ClickHouse Connector tests with ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Check for Cloud Credentials
        id: check-cloud-credentials
        run: |
          if [[ "${{ matrix.clickhouse }}" == "cloud" && (-z "${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}" || -z "${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}") ]]; then
            echo "SKIP_STEP=true" >> $GITHUB_ENV
          else
            echo "SKIP_STEP=false" >> $GITHUB_ENV
          fi
        shell: bash
      - uses: actions/checkout@v3
        if: env.SKIP_STEP != 'true'
      - name: Set up JDK 21
        if: env.SKIP_STEP != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
      - name: Setup and execute Gradle 'test' task
        if: env.SKIP_STEP != 'true'
        uses: gradle/gradle-build-action@v2
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
          CLICKHOUSE_CLOUD_HOST: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_HOST_SMT }}
          CLICKHOUSE_CLOUD_PASSWORD: ${{ secrets.INTEGRATIONS_TEAM_TESTS_CLOUD_PASSWORD_SMT }}
        with:
          arguments: :flink-connector-clickhouse-2.0.0:runScalaTests